const meals=[
{id:1,name:'Creamy Ramen Upgrade',emoji:'🍜',bg:'linear-gradient(135deg,#ff7a18,#ffcf5a)',mood:['comfort','lazy','craving'],budget:'broke',energy:'low',time:'fast',ingredients:['ramen','egg','cheese','hot sauce'],desc:'Cheap ramen acting real brand new with egg, cheese, and sauce.',steps:['Boil noodles with less water than normal.','Stir in seasoning, cheese, and a beaten egg.','Finish with hot sauce or chili crisp.'],tags:['broke','fast','comfort']},
{id:2,name:'Loaded Air Fryer Fries',emoji:'🍟',bg:'linear-gradient(135deg,#f7971e,#ffd200)',mood:['craving','chaos','lazy'],budget:'normal',energy:'low',time:'fast',ingredients:['fries','cheese','bacon','chicken'],desc:'Fries turned into dinner because nobody is judging over here.',steps:['Air fry fries until crispy.','Top with cheese, protein, and sauce.','Melt for 2 minutes and eat immediately.'],tags:['air fryer','messy','fun']},
{id:3,name:'Chicken Rice Bowl',emoji:'🍚',bg:'linear-gradient(135deg,#58e38b,#12c2e9)',mood:['healthy','comfort'],budget:'normal',energy:'medium',time:'medium',ingredients:['chicken','rice','vegetables','sauce'],desc:'The reliable meal that says “I tried” without doing too much.',steps:['Heat rice and veggies.','Cook or warm seasoned chicken.','Add sauce and mix into a bowl.'],tags:['balanced','filling','easy']},
{id:4,name:'Taco Night Remix',emoji:'🌮',bg:'linear-gradient(135deg,#ff512f,#dd2476)',mood:['craving','date','chaos'],budget:'normal',energy:'medium',time:'medium',ingredients:['tortilla','ground beef','chicken','cheese'],desc:'Tacos fix moods. That is basically science.',steps:['Cook seasoned meat.','Warm tortillas.','Add cheese, toppings, and sauce.'],tags:['crowd pleaser','quick','date night']},
{id:5,name:'Egg Fried Rice',emoji:'🍳',bg:'linear-gradient(135deg,#fceabb,#f8b500)',mood:['lazy','comfort','healthy'],budget:'broke',energy:'low',time:'fast',ingredients:['rice','egg','soy sauce','vegetables'],desc:'Leftover rice finally gets its moment.',steps:['Scramble eggs in a pan.','Add rice and veggies.','Season with soy sauce and garlic.'],tags:['leftovers','cheap','fast']},
{id:6,name:'Spicy Tuna Melt',emoji:'🥪',bg:'linear-gradient(135deg,#4facfe,#00f2fe)',mood:['comfort','lazy'],budget:'broke',energy:'low',time:'fast',ingredients:['tuna','bread','cheese','mayo'],desc:'Pantry meal with main-character energy.',steps:['Mix tuna with mayo and hot sauce.','Put on bread with cheese.','Toast until melty.'],tags:['pantry','fast','cheap']},
{id:7,name:'Salmon Rice Plate',emoji:'🐟',bg:'linear-gradient(135deg,#36d1dc,#5b86e5)',mood:['healthy','date'],budget:'treat',energy:'medium',time:'medium',ingredients:['salmon','rice','vegetables'],desc:'The “let me eat like I have my life together” plate.',steps:['Season salmon.','Bake or pan-sear.','Serve with rice and vegetables.'],tags:['protein','fresh','premium']},
{id:8,name:'Pizza Quesadilla',emoji:'🍕',bg:'linear-gradient(135deg,#ee0979,#ff6a00)',mood:['craving','chaos','lazy'],budget:'broke',energy:'low',time:'fast',ingredients:['tortilla','cheese','pepperoni','sauce'],desc:'Pizza and quesadilla had a messy little baby.',steps:['Fill tortilla with cheese and toppings.','Toast in skillet.','Dip in marinara.'],tags:['fun','fast','kid energy']},
{id:9,name:'Big Salad That Actually Eats',emoji:'🥗',bg:'linear-gradient(135deg,#11998e,#38ef7d)',mood:['healthy'],budget:'normal',energy:'medium',time:'fast',ingredients:['lettuce','chicken','egg','cheese'],desc:'Not a sad salad. A salad with bills to pay.',steps:['Add greens.','Pile on protein, cheese, and crunch.','Use a dressing you actually like.'],tags:['healthy-ish','protein','fresh']},
{id:10,name:'Grilled Cheese & Soup',emoji:'🧀',bg:'linear-gradient(135deg,#ff9966,#ff5e62)',mood:['comfort','lazy'],budget:'broke',energy:'low',time:'fast',ingredients:['bread','cheese','soup'],desc:'Soft life. Warm bowl. Crisis postponed.',steps:['Make grilled cheese.','Heat soup.','Dip aggressively.'],tags:['cozy','cheap','classic']},
{id:11,name:'Wing Night Plate',emoji:'🍗',bg:'linear-gradient(135deg,#cb2d3e,#ef473a)',mood:['craving','chaos'],budget:'treat',energy:'low',time:'fast',ingredients:['wings','fries','sauce'],desc:'For when your spirit said sauce, not salad.',steps:['Bake or air fry wings.','Toss in sauce.','Add fries or slaw.'],tags:['game night','saucy','treat']},
{id:12,name:'Shrimp Fried Rice',emoji:'🍤',bg:'linear-gradient(135deg,#ff7e5f,#feb47b)',mood:['comfort','craving'],budget:'normal',energy:'medium',time:'medium',ingredients:['shrimp','rice','egg','vegetables'],desc:'Leftover rice glow-up. Very grown. Very tasty.',steps:['Scramble egg.','Cook shrimp and veggies.','Add rice and soy sauce.'],tags:['leftovers','seafood','quick']},
{id:13,name:'Burger Bowl',emoji:'🍔',bg:'linear-gradient(135deg,#8e2de2,#ff6a00)',mood:['craving','healthy'],budget:'normal',energy:'medium',time:'medium',ingredients:['ground beef','lettuce','cheese','pickles'],desc:'Burger energy without committing to the bun drama.',steps:['Cook seasoned beef.','Layer lettuce, cheese, pickles, and sauce.','Add fries if the spirit moves you.'],tags:['low carb-ish','filling','fun']},
{id:14,name:'Date Night Alfredo',emoji:'🍝',bg:'linear-gradient(135deg,#fc466b,#3f5efb)',mood:['date','comfort'],budget:'treat',energy:'high',time:'slow',ingredients:['pasta','chicken','cream','cheese'],desc:'Romantic enough to count, easy enough to survive.',steps:['Cook pasta.','Cook chicken.','Make creamy sauce and combine.'],tags:['date night','creamy','premium']},
{id:15,name:'Baked Potato Bar',emoji:'🥔',bg:'linear-gradient(135deg,#b79891,#94716b)',mood:['comfort','lazy'],budget:'broke',energy:'medium',time:'slow',ingredients:['potato','cheese','bacon','chicken'],desc:'A potato becomes dinner when you stop playing with it.',steps:['Bake or microwave potato.','Split and fluff.','Load with toppings.'],tags:['cheap','filling','custom']},
{id:16,name:'Rotisserie Chicken Wrap',emoji:'🌯',bg:'linear-gradient(135deg,#f12711,#f5af19)',mood:['lazy','healthy'],budget:'normal',energy:'low',time:'fast',ingredients:['chicken','tortilla','lettuce','cheese'],desc:'Assembly-only dinner. We love boundaries.',steps:['Add chicken to tortilla.','Add veggies and sauce.','Wrap and toast if desired.'],tags:['fast','protein','easy']},
{id:17,name:'Pancake Stack',emoji:'🥞',bg:'linear-gradient(135deg,#d1913c,#ffd194)',mood:['comfort','chaos'],budget:'broke',energy:'medium',time:'medium',ingredients:['pancake mix','egg','milk'],desc:'Dessert pretending to be dinner. Respect.',steps:['Mix batter.','Cook pancakes.','Top with butter, syrup, or fruit.'],tags:['sweet','cheap','comfort']},
{id:18,name:'Leftover Remix Bowl',emoji:'🍲',bg:'linear-gradient(135deg,#00b09b,#96c93d)',mood:['chaos','lazy'],budget:'broke',energy:'low',time:'fast',ingredients:['rice','chicken','vegetables','eggs','sauce'],desc:'Throw leftovers in a bowl and call it strategy.',steps:['Pick a base.','Add leftovers.','Sauce it up and heat.'],tags:['leftovers','smart','fast']},
{id:19,name:'Breakfast-for-Dinner Tacos',emoji:'🌯',bg:'linear-gradient(135deg,#ffe259,#ffa751)',mood:['comfort','chaos','lazy'],budget:'broke',energy:'medium',time:'fast',ingredients:['eggs','tortilla','cheese','sausage'],desc:'Because breakfast has no bedtime.',steps:['Scramble eggs.','Add cheese and sausage.','Wrap in tortillas with sauce.'],tags:['breakfast','cheap','fun']},
{id:20,name:'Fancy Frozen Pizza',emoji:'🍕',bg:'linear-gradient(135deg,#ff416c,#ff4b2b)',mood:['lazy','craving'],budget:'normal',energy:'low',time:'medium',ingredients:['frozen pizza','cheese','pepperoni','hot honey'],desc:'A frozen pizza glow-up so good it deserves a fake accent.',steps:['Add extra cheese and toppings.','Bake until crispy.','Finish with hot honey or ranch.'],tags:['lazy','upgrade','craving']},
{id:21,name:'Chicken Caesar Wrap',emoji:'🥙',bg:'linear-gradient(135deg,#56ab2f,#a8e063)',mood:['healthy','lazy'],budget:'normal',energy:'low',time:'fast',ingredients:['chicken','tortilla','lettuce','dressing'],desc:'Fresh enough to feel responsible. Easy enough to actually do.',steps:['Add chicken and lettuce to tortilla.','Drizzle dressing.','Wrap tight and cut.'],tags:['fresh','fast','lunch']},
{id:22,name:'Garlic Butter Noodles',emoji:'🍜',bg:'linear-gradient(135deg,#f7971e,#ffd200)',mood:['comfort','lazy'],budget:'broke',energy:'low',time:'fast',ingredients:['pasta','butter','garlic','cheese'],desc:'Plain pasta said, “watch this.”',steps:['Cook pasta.','Melt butter with garlic.','Toss with cheese and pepper.'],tags:['cheap','comfort','pantry']},
{id:23,name:'BBQ Chicken Nachos',emoji:'🧀',bg:'linear-gradient(135deg,#e65c00,#f9d423)',mood:['craving','chaos'],budget:'normal',energy:'low',time:'fast',ingredients:['chips','chicken','cheese','bbq sauce'],desc:'Crunchy, messy, and not here to be elegant.',steps:['Layer chips, chicken, and cheese.','Bake or microwave until melty.','Drizzle BBQ sauce.'],tags:['snack dinner','messy','fast']},
{id:24,name:'Turkey Club Sandwich',emoji:'🥪',bg:'linear-gradient(135deg,#8e9eab,#eef2f3)',mood:['lazy','healthy'],budget:'normal',energy:'low',time:'fast',ingredients:['bread','turkey','bacon','lettuce'],desc:'A sandwich that showed up to work dressed business casual.',steps:['Toast bread.','Layer turkey, bacon, lettuce, and sauce.','Cut and serve with chips.'],tags:['classic','quick','lunch']}
];

let state={mood:'comfort',budget:'broke',energy:'low',time:'fast',saved:JSON.parse(localStorage.getItem('wteSaved')||'[]'),swipe:null,vibeIndex:0};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function saveState(){localStorage.setItem('wteSaved',JSON.stringify(state.saved))}
function tapBuzz(){try{navigator.vibrate&&navigator.vibrate(12)}catch(e){}}
function toast(msg){tapBuzz();const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function nav(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='savedScreen')renderSaved();if(id==='swipeScreen'&&!state.swipe)newSwipe();}
function scoreMeal(meal){let score=0;if(meal.mood.includes(state.mood))score+=4;if(meal.budget===state.budget)score+=3;if(meal.energy===state.energy)score+=3;if(meal.time===state.time)score+=3;const ing=$('#ingredientInput')?.value.toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)||[];ing.forEach(i=>{if(meal.ingredients.some(m=>m.includes(i)||i.includes(m)))score+=2});return score;}
function foodPhoto(meal){return `<div class="food-photo" style="--food-bg:${meal.bg}"><div class="food-emoji">${meal.emoji}</div></div>`}
function mealCard(meal,showScore=false){const saved=state.saved.includes(meal.id);return `<article class="meal-card"><div class="meal-card-top">${foodPhoto(meal)}<div><h3>${meal.name}</h3><p>${meal.desc}</p><div class="tag-row">${meal.tags.map(t=>`<span class="tag">${t}</span>`).join('')}${showScore?`<span class="tag">${scoreMeal(meal)} pts</span>`:''}</div></div></div><div class="meal-actions"><button class="small-btn" onclick="openRecipe(${meal.id})">Recipe</button><button class="small-btn" onclick="toggleSave(${meal.id})">${saved?'Saved ❤️':'Save 🤍'}</button></div></article>`}
function renderTrending(){const picks=meals.filter(m=>m.mood.includes('craving')||m.mood.includes('comfort')).slice(0,10);$('#trendingMeals').innerHTML=picks.map(m=>`<button class="trend-card" onclick="showHomeResult(${m.id})">${foodPhoto(m)}<h4>${m.name}</h4><p>${m.desc}</p></button>`).join('')}
const vibes=[
{title:'Comfort food with zero drama.',text:'For when your stomach wants a hug and your patience clocked out.',filter:{mood:'comfort'}},
{title:'Broke but still eating good.',text:'Cheap meals that do not taste like financial distress.',filter:{budget:'broke'}},
{title:'Lazy mode, professionally.',text:'Bare minimum effort. Maximum “okay, this actually hits.”',filter:{energy:'low'}},
{title:'Craving chaos accepted.',text:'For when dinner needs to be messy, loud, saucy, and slightly irresponsible.',filter:{mood:'chaos'}},
{title:'Date night without the group chat debate.',text:'Food that feels cute without requiring a reservation or emotional labor.',filter:{mood:'date'}}
];
function renderVibe(){const v=vibes[state.vibeIndex%vibes.length];const title=$('#vibeTitle');const text=$('#vibeText');if(title)title.textContent=v.title;if(text)text.textContent=v.text;renderTonightFeed(v.filter)}
function renderTonightFeed(filter={}){const pool=meals.filter(m=>Object.entries(filter).every(([k,v])=>Array.isArray(m[k])?m[k].includes(v):m[k]===v));const picks=(pool.length?pool:meals).slice(0,5);const wrap=$('#tonightFeed');if(!wrap)return;wrap.innerHTML=picks.map(m=>`<button class="feed-card" onclick="showHomeResult(${m.id});document.getElementById('homeResult').scrollIntoView({behavior:'smooth',block:'center'})">${foodPhoto(m)}<div><h4>${m.name}</h4><p>${m.desc}</p><div class="feed-meta"><span>${m.budget}</span><span>${m.time}</span><span>${m.energy} energy</span></div></div></button>`).join('')}
function shareMeal(meal){const text=`WhatToEat picked ${meal.name} for me. ${meal.desc}`;if(navigator.share){navigator.share({title:'WhatToEat',text}).catch(()=>{})}else{navigator.clipboard?.writeText(text);toast('Meal idea copied') }}
function showHomeResult(id){const meal=meals.find(m=>m.id===id);const box=$('#homeResult');box.innerHTML=`<p class="eyebrow">Today's pick</p>${mealCard(meal)}`;box.classList.add('show');}
function randomMeal(filter={}){let pool=meals.filter(m=>Object.entries(filter).every(([k,v])=>Array.isArray(m[k])?m[k].includes(v):m[k]===v));if(!pool.length)pool=meals;return pool[Math.floor(Math.random()*pool.length)]}
function findMatches(){const ranked=[...meals].map(m=>({m,score:scoreMeal(m)})).sort((a,b)=>b.score-a.score).slice(0,7);$('#matchSummary').textContent=`Top ${ranked.length} matches for your current food mood.`;$('#smartResults').innerHTML=ranked.map(x=>mealCard(x.m,true)).join('');setTimeout(()=>$('#smartResults').scrollIntoView({behavior:'smooth',block:'start'}),80)}
function toggleSave(id){if(state.saved.includes(id)){state.saved=state.saved.filter(x=>x!==id);toast('Removed from saved')}else{state.saved.unshift(id);toast('Saved for later')}saveState();renderSaved();if($('#smartScreen').classList.contains('active'))findMatches();}
function renderSaved(){const savedMeals=state.saved.map(id=>meals.find(m=>m.id===id)).filter(Boolean);$('#savedMeals').innerHTML=savedMeals.length?savedMeals.map(m=>mealCard(m)).join(''):`<section class="card empty-card"><div class="food-emoji">❤️</div><h2>No saved meals yet</h2><p class="muted">Swipe or save meals when something looks good enough to remember.</p><button class="primary-btn" data-nav="swipeScreen">Go swipe food</button></section>`;$$('#savedMeals [data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)))}
function openRecipe(id){const m=meals.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-food">${foodPhoto(m)}</div><p class="eyebrow">Quick recipe</p><h2>${m.name}</h2><p class="muted">${m.desc}</p><h3>What you need</h3><div class="tag-row">${m.ingredients.map(i=>`<span class="tag">${i}</span>`).join('')}</div><h3 style="margin-top:18px">Steps</h3><ol class="recipe-list">${m.steps.map(s=>`<li>${s}</li>`).join('')}</ol>`;$('#modalBackdrop').classList.add('show');$('#recipeModal').classList.add('show');$('#recipeModal').setAttribute('aria-hidden','false')}
function closeRecipe(){ $('#modalBackdrop').classList.remove('show');$('#recipeModal').classList.remove('show');$('#recipeModal').setAttribute('aria-hidden','true')}
function swipeMarkup(m){return `<div class="match-badge">${m.budget} • ${m.time}</div><div class="swipe-visual" style="--food-bg:${m.bg}"><div class="food-emoji">${m.emoji}</div></div><div class="swipe-info"><p class="eyebrow">${m.tags[0]}</p><h2>${m.name}</h2><p class="muted">${m.desc}</p><div class="tag-row">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div>`}
function newSwipe(avoid){let m=randomMeal();if(avoid){let tries=0;while(m.id===avoid&&tries<10){m=randomMeal();tries++}}state.swipe=m;const card=$('#swipeCard');card.classList.remove('throw-left','throw-right');card.innerHTML=swipeMarkup(m)}
function animateSwipe(dir,then){tapBuzz();const card=$('#swipeCard');card.classList.add(dir==='left'?'throw-left':'throw-right');setTimeout(()=>{then?.();newSwipe(state.swipe?.id)},230)}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
$$('.chip-grid').forEach(group=>group.addEventListener('click',e=>{if(!e.target.classList.contains('chip'))return;group.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));e.target.classList.add('active');state[group.dataset.filterGroup]=e.target.dataset.value;}));
$('#findMealBtn').addEventListener('click',findMatches);
$('#quickRandom').addEventListener('click',()=>showHomeResult(randomMeal().id));
$('#lazyMode').addEventListener('click',()=>showHomeResult(randomMeal({energy:'low'}).id));
$('#coupleMode').addEventListener('click',()=>showHomeResult(randomMeal({mood:'date'}).id));
$('#chaosBtn').addEventListener('click',()=>{showHomeResult(randomMeal({mood:'chaos'}).id);toast('Chaos meal activated')});
$('#passBtn').addEventListener('click',()=>animateSwipe('left'));
$('#saveSwipeBtn').addEventListener('click',()=>state.swipe&&animateSwipe('right',()=>toggleSave(state.swipe.id)));
$('#recipeSwipeBtn').addEventListener('click',()=>state.swipe&&openRecipe(state.swipe.id));
$('#shareSwipeBtn')?.addEventListener('click',()=>state.swipe&&shareMeal(state.swipe));
$('#vibeRefresh')?.addEventListener('click',()=>{state.vibeIndex++;renderVibe();toast('New dinner vibe loaded')});
$('#closeModal').addEventListener('click',closeRecipe);$('#modalBackdrop').addEventListener('click',closeRecipe);
let startX=0,currentX=0,dragging=false;const swipeCard=$('#swipeCard');
swipeCard.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;swipeCard.setPointerCapture(e.pointerId)});
swipeCard.addEventListener('pointermove',e=>{if(!dragging)return;currentX=e.clientX-startX;swipeCard.style.transform=`translateX(${currentX}px) rotate(${currentX/18}deg)`});
swipeCard.addEventListener('pointerup',()=>{if(!dragging)return;dragging=false;swipeCard.style.transform='';if(currentX>95){animateSwipe('right',()=>toggleSave(state.swipe.id))}else if(currentX<-95){animateSwipe('left')}currentX=0});

const deckFilters={payday:{budget:'treat'},broke:{budget:'broke'},lazy:{energy:'low'},late:{mood:'chaos'}};
function renderCravingLanes(){const lanes=[
  {emoji:'🍗',title:'Protein drama',sub:'Chicken, bowls, and filling food.',filter:{mood:'healthy'}},
  {emoji:'🍜',title:'Cozy bowl stuff',sub:'Soup, noodles, rice, comfort.',filter:{mood:'comfort'}},
  {emoji:'🌮',title:'Messy cravings',sub:'Saucy food with no manners.',filter:{mood:'chaos'}},
  {emoji:'🥪',title:'No-cook-ish',sub:'Fast meals for tired people.',filter:{energy:'low'}}
];const wrap=document.getElementById('cravingLanes');if(!wrap)return;wrap.innerHTML=lanes.map((l,i)=>`<button class="lane-card" data-lane="${i}"><span>${l.emoji}</span><b>${l.title}</b><small>${l.sub}</small></button>`).join('');wrap.querySelectorAll('.lane-card').forEach((btn,i)=>btn.addEventListener('click',()=>{const meal=randomMeal(lanes[i].filter);showHomeResult(meal.id);toast(lanes[i].title+' loaded');document.getElementById('homeResult').scrollIntoView({behavior:'smooth',block:'center'});}));}

$$('.deck-chip').forEach(btn=>btn.addEventListener('click',()=>{const meal=randomMeal(deckFilters[btn.dataset.deck]||{});showHomeResult(meal.id);toast(btn.textContent+' pick loaded');document.getElementById('homeResult').scrollIntoView({behavior:'smooth',block:'center'});}));
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
renderTrending();renderVibe();renderCravingLanes();renderSaved();newSwipe();showHomeResult(randomMeal().id);
