const meals=[
{id:1,name:'Air Fryer Chicken Wrap',emoji:'🌯',mood:'lazy',budget:'medium',energy:'low',time:'12 min',photo:'linear-gradient(135deg,#b6451e,#ffb347)',desc:'Crispy chicken, tortilla, sauce, done. No TED Talk required.',why:'Because you want real food without starting a whole kitchen documentary.',steps:['Air fry chicken strips or nuggets.','Warm tortilla.','Add lettuce, cheese, sauce.','Wrap and eat before anyone asks for a bite.']},
{id:2,name:'Broke Bestie Ramen Bowl',emoji:'🍜',mood:'broke',budget:'low',energy:'low',time:'8 min',photo:'linear-gradient(135deg,#9b2c1f,#ffcc66)',desc:'Ramen with egg, cheese, and audacity.',why:'Because your wallet said “please be serious” but your stomach still deserves flavor.',steps:['Boil ramen.','Stir in egg near the end.','Add cheese or hot sauce.','Act like you invented comfort.']},
{id:3,name:'Lazy Garlic Butter Pasta',emoji:'🍝',mood:'comfort',budget:'low',energy:'medium',time:'15 min',photo:'linear-gradient(135deg,#7b2d13,#f6c86a)',desc:'Pasta, butter, garlic, cheese. Respectfully elite.',why:'Because comfort food should not require a culinary degree or emotional labor.',steps:['Boil pasta.','Melt butter with garlic seasoning.','Toss pasta with cheese.','Add pepper and eat dramatically.']},
{id:4,name:'Sheet Pan Sausage & Rice',emoji:'🍛',mood:'comfort',budget:'medium',energy:'medium',time:'20 min',photo:'linear-gradient(135deg,#5e2612,#f28c28)',desc:'Big plate energy with almost no thinking.',why:'Because you need something filling that feels like somebody cared, even if that somebody was tired.',steps:['Slice sausage.','Heat with veggies.','Serve over rice.','Add sauce if life feels dry.']},
{id:5,name:'Healthy-ish Salmon Bowl',emoji:'🍣',mood:'healthy-ish',budget:'high',energy:'medium',time:'18 min',photo:'linear-gradient(135deg,#174d3f,#ff8f70)',desc:'Feels responsible without tasting like punishment.',why:'Because you want to feel grown, balanced, and slightly better than yesterday.',steps:['Cook salmon.','Add rice and veggies.','Drizzle sauce.','Pretend you meal-prep regularly.']},
{id:6,name:'Chaos Breakfast Dinner',emoji:'🍳',mood:'chaos',budget:'low',energy:'low',time:'10 min',photo:'linear-gradient(135deg,#3b1d0f,#ffd166)',desc:'Eggs, toast, whatever meat is around. Dinner rules are fake.',why:'Because it is night, you want breakfast, and society cannot stop you.',steps:['Scramble eggs.','Toast bread.','Add bacon/sausage if available.','Eat like it was always the plan.']},
{id:7,name:'Pizza Quesadilla',emoji:'🍕',mood:'lazy',budget:'low',energy:'low',time:'9 min',photo:'linear-gradient(135deg,#7d1d1d,#ff7a1a)',desc:'When pizza and quesadilla make a questionable but delicious decision.',why:'Because you need dopamine, cheese, and a meal that understands your current standards.',steps:['Add cheese and pepperoni to tortilla.','Fold and pan-toast.','Dip in marinara.','Say “this counts.”']},
{id:8,name:'Tuna Melt Situation',emoji:'🥪',mood:'broke',budget:'low',energy:'medium',time:'12 min',photo:'linear-gradient(135deg,#26384d,#d8a15d)',desc:'Pantry meal that shows up when the fridge is embarrassing.',why:'Because canned tuna has been waiting for its redemption arc.',steps:['Mix tuna with mayo/seasoning.','Put on bread with cheese.','Toast in pan.','Eat hot. Judge nobody.']},
{id:9,name:'Loaded Nugget Bowl',emoji:'🍗',mood:'chaos',budget:'medium',energy:'low',time:'11 min',photo:'linear-gradient(135deg,#693011,#ffb703)',desc:'Chicken nuggets over fries/rice with sauce like you meant to do it.',why:'Because sometimes the meal is not classy — it is effective.',steps:['Cook nuggets.','Add fries, rice, or whatever base you have.','Drizzle ranch, buffalo, or BBQ.','Add cheese if you want chaos.']},
{id:10,name:'Snack Plate Dinner',emoji:'🧀',mood:'lazy',budget:'medium',energy:'low',time:'5 min',photo:'linear-gradient(135deg,#3b2a16,#ffd166)',desc:'Cheese, crackers, fruit, meat, pickles. A board without the influencer pressure.',why:'Because you want to eat, not perform dinner for an imaginary audience.',steps:['Grab 3 salty things.','Grab 1 sweet thing.','Add cheese or protein.','Put it on a plate so it feels official.']}
];
let favorites=JSON.parse(localStorage.getItem('wte_favorites_v30')||'[]');let currentSwipe=0;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function pick(arr=meals){return arr[Math.floor(Math.random()*arr.length)]||meals[0]}
function scoreMeal(meal,mood,budget,energy){return (meal.mood===mood?3:0)+(meal.budget===budget?2:0)+(meal.energy===energy?2:0)}
function card(meal,showWhy=true){return `<article class="meal-card"><div class="meal-photo" style="background:${meal.photo}"><span class="emoji-float">${meal.emoji}</span></div><h3>${meal.name}</h3><p>${meal.desc}</p>${showWhy?`<div class="why-box"><b>Why this works:</b> ${meal.why}</div>`:''}<div class="badges"><span class="badge">${meal.time}</span><span class="badge">${meal.budget} budget</span><span class="badge">${meal.energy} energy</span><span class="badge">${meal.mood}</span></div><div class="card-actions"><button onclick="saveMeal(${meal.id})">Save</button><button onclick="openRecipe(${meal.id})">Recipe</button></div></article>`}
function renderDaily(){const m=pick(meals);$('#dailyPick').innerHTML=card(m)}
function renderTrends(){const trend=[...meals].sort(()=>Math.random()-.5).slice(0,5);$('#trendFeed').innerHTML=trend.map(m=>`<button class="trend-card" onclick="openRecipe(${m.id})"><div class="trend-img" style="background:${m.photo}">${m.emoji}</div><div><b>${m.name}</b><small>${m.time} • ${m.mood}</small></div></button>`).join('')}
function renderMeals(){const shuffled=[...meals].sort(()=>Math.random()-.5);$('#mealList').innerHTML=shuffled.map(m=>card(m,true)).join('')}
function renderFavorites(){const favMeals=meals.filter(m=>favorites.includes(m.id));$('#favoritesList').innerHTML=favMeals.length?favMeals.map(m=>card(m,true)).join(''):`<div class="panel-card"><p class="tag">Empty plate</p><h2>No saved meals yet.</h2><p>Save something before your hunger starts making financial decisions.</p></div>`}
function saveMeal(id){if(!favorites.includes(id)){favorites.push(id);localStorage.setItem('wte_favorites_v30',JSON.stringify(favorites));toast('Saved. Future you says thanks.');renderFavorites()}else toast('Already saved, bestie.')}
function openRecipe(id){const m=meals.find(x=>x.id===id);$('#recipeContent').innerHTML=`<p class="tag">Quick recipe</p><h2>${m.emoji} ${m.name}</h2><p>${m.desc}</p><div class="why-box"><b>AI-style take:</b> ${m.why}</div><ol>${m.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="badges"><span class="badge">${m.time}</span><span class="badge">${m.budget}</span><span class="badge">${m.energy}</span></div>`;$('#recipeModal').classList.add('show')}
function renderSwipe(){const m=meals[currentSwipe%meals.length];$('#swipeCard').innerHTML=`<div class="swipe-photo" style="background:${m.photo}"><div class="big-food">${m.emoji}</div></div><div class="swipe-info"><p class="tag">${m.mood} mood • ${m.time}</p><h2>${m.name}</h2><p>${m.desc}</p><div class="why-box"><b>Why you might want this:</b> ${m.why}</div><div class="badges"><span class="badge">${m.budget} budget</span><span class="badge">${m.energy} energy</span></div></div>`}
function nextSwipe(){currentSwipe++;renderSwipe()}
function smartPick(){const mood=$('#moodSelect').value,budget=$('#budgetSelect').value,energy=$('#energySelect').value;let matches=[...meals].sort((a,b)=>scoreMeal(b,mood,budget,energy)-scoreMeal(a,mood,budget,energy));const top=matches[0];$('#smartResult').innerHTML=`<div class="match-summary"><p class="tag">Your food read</p><h2>${top.emoji} ${top.name} is the move.</h2><p>Because you picked <b>${mood}</b>, <b>${budget}</b> budget, and <b>${energy}</b> energy. The app says stop negotiating with hunger.</p></div>`+matches.slice(0,3).map(m=>card(m,true)).join('')}
function nav(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='favoritesScreen')renderFavorites();if(id==='mealsScreen')renderMeals()}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
$$('.mood-chip').forEach(b=>b.addEventListener('click',()=>{$$('.mood-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m=pick(meals.filter(x=>x.mood===b.dataset.mood));$('#heroTitle').textContent=`${b.textContent} mood detected.`;$('#heroText').textContent=m.why;$('#aiPanel').innerHTML=`<p class="tag">AI-style read</p><h3>${b.textContent} mood means: ${m.name}.</h3><p>${m.why}</p>`;$('#dailyPick').innerHTML=card(m)}));
$('#refreshDaily').onclick=()=>{renderDaily();renderTrends();toast('Fresh cravings loaded.')};$('#surpriseBtn').onclick=()=>{renderDaily();renderTrends();toast('New food chaos loaded.')};$('#shuffleMeals').onclick=renderMeals;$('#smartPickBtn').onclick=smartPick;$('#nextSwipe').onclick=nextSwipe;$('#skipSwipe').onclick=()=>{toast('Skipped. The plate was not the vibe.');nextSwipe()};$('#saveSwipe').onclick=()=>saveMeal(meals[currentSwipe%meals.length].id);$('#recipeSwipe').onclick=()=>openRecipe(meals[currentSwipe%meals.length].id);$('#closeModal').onclick=()=>$('#recipeModal').classList.remove('show');$('#recipeModal').addEventListener('click',e=>{if(e.target.id==='recipeModal')e.currentTarget.classList.remove('show')});
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js?v=30').catch(()=>{})}
renderDaily();renderTrends();renderMeals();renderSwipe();renderFavorites();
